#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

SB_CONFIG_PARTITION_MANAGER=n

# Direct-XIP is not supported in TF-M builds
SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE=y

# Hardware Ed25519 image signature with the public key stored in the CRACEN KMU.
# The key is provisioned by the west runner at flash time, hence `--erase`/`--recover`.
SB_CONFIG_BOOT_SIGNATURE_TYPE_ED25519=y
SB_CONFIG_MCUBOOT_SIGNATURE_USING_KMU=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${SB_APPLICATION_CONFIG_DIR}/boot_signature_key_file_ed25519.pem"
SB_CONFIG_MCUBOOT_SIGNATURE_USING_KMU=y
SB_CONFIG_MCUBOOT_GENERATE_DEFAULT_KEY_FILE=y

# Select the secure storage for provisioning data
SB_CONFIG_BT_FAST_PAIR_PROVISION_SECURE_STORAGE=y
