#
# Copyright (c) 2024-2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3584

# Enable code partitioning with DTS
CONFIG_USE_DT_CODE_PARTITION=y

# Configure TF-M verbosity
CONFIG_TFM_LOG_LEVEL_SILENCE=n
CONFIG_TFM_SPM_LOG_LEVEL_DEBUG=y
CONFIG_TFM_EXCEPTION_INFO_DUMP=y

# Disable application ranging module
CONFIG_APP_RANGING=n

# Configure PSA crypto backend
CONFIG_BT_FAST_PAIR_CRYPTO_PSA=y

