#
# Copyright (c) 2024-2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3584

# Align the advertised TX power with Fast Pair expectations.
CONFIG_BT_ADV_PROV_TX_POWER_CORRECTION_VAL=-11

# Configure TF-M verbosity
CONFIG_TFM_LOG_LEVEL_SILENCE=n
CONFIG_TFM_SPM_LOG_LEVEL_DEBUG=y
CONFIG_TFM_EXCEPTION_INFO_DUMP=y

# Configure PSA crypto backend
CONFIG_BT_FAST_PAIR_CRYPTO_PSA=y

# Provision the Fast Pair data (Anti-Spoofing private key and Model ID) from the
# flash partition into the KMU and PSA Protected Storage on the first boot.
CONFIG_BT_FAST_PAIR_PROVISION=y
CONFIG_BT_FAST_PAIR_KMU_SLOT=170
CONFIG_BT_FAST_PAIR_PS_ID=1
