#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Fallback fils for plain builds - does not enable MCUBoot

# This sample describes its flash layout with devicetree partitions.
SB_CONFIG_PARTITION_MANAGER=n