#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Fallback fils for plain builds - does not enable MCUBoot

# This sample describes its flash layout with devicetree partitions.
SB_CONFIG_PARTITION_MANAGER=n

# Select the secure storage for provisioning data
SB_CONFIG_BT_FAST_PAIR_PROVISION_SECURE_STORAGE=y
SB_CONFIG_BT_FAST_PAIR_RUNTIME_PROVISIONER=y