#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# FILE_SUFFIX=mcuboot_provisioner replaces prj.conf; subsys/provisioner/prj.conf
# is merged via sysbuild.cmake add_overlay_config().

CONFIG_SETTINGS=n
CONFIG_USE_DT_CODE_PARTITION=y
