#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# FILE_SUFFIX=mcuboot_provisioner replaces prj.conf. CONFIG_PROVISIONER is set in
# sysbuild.cmake; subsys/provisioner/prj.conf is merged via add_overlay_config().

CONFIG_FP_PROVISION_DATA=y

CONFIG_SETTINGS=n
