#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
"""Decode the Fast Pair Anti-Spoofing private key at build time.

The base64-encoded key is decoded here, at build time, and emitted as a C byte
array header. This keeps the base64 form as the single Kconfig input while
avoiding any base64 decoding on the device during provisioning.
"""

import argparse
import base64
import sys

KEY_LEN = 32


def parse_arguments():
    p = argparse.ArgumentParser(
        description="Generate the Fast Pair Anti-Spoofing key header",
        allow_abbrev=False,
    )
    p.add_argument("--key", required=True,
                   help="Base64-encoded Anti-Spoofing private key")
    p.add_argument("--output", required=True, help="Path of the generated header")
    return p.parse_args()


def key_to_bytes(key_b64):
    if not key_b64:
        raise ValueError(
            "Anti-Spoofing key is empty. Set SB_CONFIG_BT_FAST_PAIR_ANTI_SPOOFING_PRIVATE_KEY."
        )

    key = base64.b64decode(key_b64, validate=True)
    if len(key) != KEY_LEN:
        raise ValueError(
            f"Anti-Spoofing key must decode to {KEY_LEN} bytes, got {len(key)}"
        )

    return key


def render_header(key):
    lines = [
        "/*",
        " * Auto-generated by fp_provision_key_gen.py - do not edit.",
        " */",
        "",
        "#ifndef FP_PROVISION_KEY_H_",
        "#define FP_PROVISION_KEY_H_",
        "",
        "#include <stdint.h>",
        "",
        f"#define FP_PROVISION_ANTI_SPOOFING_KEY_LEN {KEY_LEN}U",
        "",
        "static const uint8_t "
        "fp_provision_anti_spoofing_key[FP_PROVISION_ANTI_SPOOFING_KEY_LEN] __aligned(16) = {",
    ]

    for i in range(0, KEY_LEN, 8):
        chunk = ", ".join(f"0x{b:02x}" for b in key[i:i + 8])
        lines.append(f"\t{chunk},")

    lines += [
        "};",
        "",
        "#endif /* FP_PROVISION_KEY_H_ */",
        "",
    ]

    return "\n".join(lines)


def main():
    args = parse_arguments()

    try:
        key = key_to_bytes(args.key)
    except Exception as e:
        sys.exit(f"Failed to decode the Fast Pair Anti-Spoofing key: {e}")

    with open(args.output, "w") as f:
        f.write(render_header(key))


if __name__ == "__main__":
    main()
